config/routes.rb
Rails.application.routes.draw do
  resources :employments
  resources :employees
  root "employees#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :first_name, presence: true
    validates :first_name, length: {maximum: 25}
    validates :last_name, presence: true
    validates :first_name, length: {maximum: 50}
    validates :email, presence: true
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :phone, presence: true
end

app/models/employment.rb
class Employment < ApplicationRecord
    validates :employer, presence: true
    validates :date_started, presence: true
    validates :date_employment_ended, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
    @employments = Employment.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      respond_to do |format|
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :nickname, :email, :phone)
    end
end

app/controllers/employments_controller.rb
class EmploymentsController < ApplicationController
  before_action :set_employment, only: %i[ show edit update destroy ]

  # GET /employments or /employments.json
  def index
    @employments = Employment.all
  end

  # GET /employments/1 or /employments/1.json
  def show
  end

  # GET /employments/new
  def new
    @employment = Employment.new
  end

  # GET /employments/1/edit
  def edit
  end

  # POST /employments or /employments.json
  def create
    @employment = Employment.new(employment_params)

    if @employment.save
      respond_to do |format|
        format.html { redirect_to employment_url(@employment), notice: "Employment was successfully created." }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.turbo_stream
      end
    end
  end

  # PATCH/PUT /employments/1 or /employments/1.json
  def update
    respond_to do |format|
      if @employment.update(employment_params)
        format.html { redirect_to employment_url(@employment), notice: "Employment was successfully updated." }
        format.json { render :show, status: :ok, location: @employment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employments/1 or /employments/1.json
  def destroy
    @employment.destroy

    respond_to do |format|
      format.html { redirect_to employments_url, notice: "Employment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employment
      @employment = Employment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employment_params
      params.require(:employment).permit(:employer, :date_started, :date_employment_ended)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/employments_helper.rb
module EmploymentsHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>First name:</strong>
    <%= employee.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= employee.last_name %>
  </p>

  <p>
    <strong>Nickname:</strong>
    <%= employee.nickname %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= employee.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= employee.phone %>
  </p>

  <div>
    <%= link_to "Edit this employee", edit_employee_path(employee) %> |
    <%= button_to "Destroy this employee", employee, method: :delete %>
  </div>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, required: true %>
    <% if employee.errors[:first_name].present? %>
      <li style="color: red"><%= employee.errors.full_messages_for(:first_name).first %></li>
    <% end %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, required: true %>
    <% if employee.errors[:last_name].present? %>
      <li style="color: red"><%= employee.errors.full_messages_for(:last_name).first %></li>
    <% end %>
  </div>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
    <% if employee.errors[:nickname].present? %>
      <li style="color: red"><%= employee.errors.full_messages_for(:nickname).first %></li>
    <% end %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, required: true %>
    <% if employee.errors[:email].present? %>
      <li style="color: red"><%= employee.errors.full_messages_for(:email).first %></li>
    <% end %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, required: true %>
    <% if employee.errors[:phone].present? %>
      <li style="color: red"><%= employee.errors.full_messages_for(:phone).first %></li>
    <% end %>
  </div>

  <div>
    <%= form.submit "Save", class: "rounded-lg py-3 px-5 bg-blue-600 text-white"%>
  </div>

<% end %>

app/views/employees/create.turbo_stream.erb
<%= turbo_stream.prepend "employees", @employee %>
<%#= turbo_stream.update Employee.new, "" %>


<%#= turbo_stream.update Employment.new do %>
    <%#= render "employments/form", employment: Employment.new %>
<%# end %>


<%= turbo_stream.update "modal" do %>
    <%= tag.div data: { controller: "turbo-modal" }, class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
        <%= render "employments/form", employment: Employment.new %>
        <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
    <% end %>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Personal Data",
                    new_employee_path,
                    class: "focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900",
                    data: { turbo_frame: 'modal' } %>

<%= link_to "New Employment",
                    new_employment_path,
                    class: "focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900",
                    data: { turbo_frame: 'modal' } %>

<br>
<br>
<h2 class="text-4xl font-extrabold dark:text-white">Personal Details</h2>
<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <hr class="my-4 mx-auto w-48 h-1 bg-gray-100 rounded border-0 md:my-10 dark:bg-gray-700">
  <% end %>
</div>

<hr class="my-4 mx-auto w-48 h-1 bg-gray-100 rounded border-0 md:my-10 dark:bg-gray-700">

<h2 class="text-4xl font-extrabold dark:text-white">Employments</h2>
<div id="employments">
  <% @employments.each do |employment| %>
    <%= render employment %>
    <hr class="my-4 mx-auto w-48 h-1 bg-gray-100 rounded border-0 md:my-10 dark:bg-gray-700">
  <% end %>
</div>

app/views/employees/new.html.erb
<%#= turbo_frame_tag 'new_employee' do %>
  <%#= render "form", employee: @employee %>
<%# end %>



<%= turbo_frame_tag 'modal' do %>
  <%= tag.div data: { controller: "turbo-modal", action: "keyup@window->turbo-modal#closeWithKeyboard"}, class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
    <h1>New employee</h1>
    <%= render "form", employee: @employee %>
    <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
  <% end %>
<% end %>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

app/views/employments/_employment.html.erb
<div id="<%= dom_id employment %>">
  <p>
    <strong>Employer:</strong>
    <%= employment.employer %>
  </p>

  <p>
    <strong>Date started:</strong>
    <%= employment.date_started %>
  </p>

  <p>
    <strong>Date employment ended:</strong>
    <%= employment.date_employment_ended %>
  </p>

</div>

app/views/employments/_form.html.erb
<%= form_with(model: employment) do |form| %>

  <div>
    <%= form.label :employer, style: "display: block" %>
    <%= form.text_field :employer, required: true %>
    <% if employment.errors[:employer].present? %>
      <li style="color: red"><%= employment.errors.full_messages_for(:employer).first %></li>
    <% end %>
  </div>

  <div>
    <%= form.label :date_started, style: "display: block" %>
    <%= form.datetime_field :date_started, required: true%>
    <% if employment.errors[:date_started].present? %>
      <li style="color: red"><%= employment.errors.full_messages_for(:date_started).first %></li>
    <% end %>
  </div>

  <div>
    <%= form.label :date_employment_ended, style: "display: block" %>
    <%= form.datetime_field :date_employment_ended, required: true %>
    <% if employment.errors[:date_employment_ended].present? %>
      <li style="color: red"><%= employment.errors.full_messages_for(:date_employment_ended).first %></li>
    <% end %>
  </div>

  <div>
    <%= form.submit "Add Employment", class: "rounded-lg py-3 px-5 bg-blue-600 text-white"%>
  </div>
<% end %>

app/views/employments/create.turbo_stream.erb
<%= turbo_stream.prepend "employments", @employment %>
<%= turbo_stream.update 'modal' do %>

    <%= tag.div data: { controller: "turbo-modal" }, class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
        <% if @employment.errors.any? %>
            <%= render "form", employment: @employment %>
        <% else %>
            <%= render "form", employment: Employment.new %>
        <% end %>
        <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
    <% end %>

    
<% end %>

app/views/employments/edit.html.erb
<h1>Editing employment</h1>

<%= render "form", employment: @employment %>

<br>

<div>
  <%= link_to "Show this employment", @employment %> |
  <%= link_to "Back to employments", employments_path %>
</div>

app/views/employments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employments</h1>

<div id="employments">
  <% @employments.each do |employment| %>
    <%= render employment %>
    <p>
      <%= link_to "Show this employment", employment %>
    </p>
  <% end %>
</div>

<%= link_to "New employment", new_employment_path %>

app/views/employments/new.html.erb
<%= turbo_frame_tag 'modal' do %>
  <%= tag.div data: { controller: "turbo-modal", action: "keyup@window->turbo-modal#closeWithKeyboard" }, class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do %>
    <h1>New employment</h1>
    <%= render "form", employment: @employment %>
    <%= button_tag "Close", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white" %>
  <% end %>
<% end %>

app/views/employments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employment %>

<div>
  <%= link_to "Edit this employment", edit_employment_path(@employment) %> |
  <%= link_to "Back to employments", employments_path %>

  <%= button_to "Destroy this employment", @employment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingExercise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="max-w-7xl mx-auto mt-8">
    <%= turbo_frame_tag "modal" %>
    <%= yield %>
  </body>
</html>